### ISSUE TITLE
Add integration test running in Exasol

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-driver-lua#23]
To ensure that the driver runs inside an Exasol database we need to add integration tests.

Precondition: Exasol Docker container that includes dependencies.

**Comment by redcatbear** [comment]
@kaklakariada please specify required dependencies in this issue ticket and check if they are in the latest images.

**Comment by kaklakariada** [comment]
The following Lua modules are required to be installed in the database:

* luasocket
* luasec
* luaossl
* lua-cjson
* base64

Some of them are already available in Exasol.

Other libraries (e.g. remotelog) can be packed using amalgamation.
